ТЗ 6
Gagarskiy-Andrey/java-kanban pull request #1
Opened 2024-09-25 14:53 UTC by Gagarskiy-Andrey

2024-09-26 14:46 UTC, YazykovMikhail requested changes

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +    private Integer lastId = null;
это поле лишние

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +    private void linkLast(Task task) {
Вот так будет получше
```
	private void linkLast(Task task) {
		final Node node = new Node(tail, task, null);
		if (first == null) {
			first = node;
		} else {
			last.next = node;
		}
		last = node;
	}
```

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +        if (history.containsKey(task.getId())) {
У тьбя тут двойной поиск сначала для проверки потом для удаления, вызывай просто
```
		final int id = task.getId();
		remove(id);
```
а в 	remove я покажу как сделать

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +            history.put(task.getId(), last);
Метод linkLast не должен добавлять, он настраивает ссылки. 
Для доабвления есть метод add

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +        linkLast(anotherTask);
linkLast(task);
		history.put(id, last);

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
```
	public void remove(int id) {
		final Node node = history.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```
И получается без повторных проверок

2024-09-26 14:46 UTC, YazykovMikhail commented on src/manager/InMemoryHistoryManager.java
> +    public List<Task> getHistory() {
Лучше учитывать все варианты сразу:

	public List<Task> getHistory() {
		ArrayList<Task> tasks = new ArrayList<>();

		Node node = first;
		while (node != null) {
			tasks.add(node.task);
			node = node.next;
		}
		return tasks;
	}

2024-09-28 09:24 UTC, Gagarskiy-Andrey commented on src/manager/InMemoryHistoryManager.java
> +    public List<Task> getHistory() {
Лихо!

2024-09-28 21:49 UTC, YazykovMikhail approved these changes

2024-10-14 13:52 UTC, merged